name: example
description: "Demonstrates how to use the islamic_hijri_calendar_rhg package with multi-language support."
publish_to: 'none' # Standard for package examples to prevent accidental publishing of the example itself

version: 1.1.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  islamic_hijri_calendar_rhg:
    path: ../
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
